# 
# xorshift128+ State Reconstruction with Z3
# 
# This script uses Z3 as a constraint solver to:
# 1. Reconstruct the internal state of the xorshift128+ PRNG
# 2. Predict the next 5 random numbers that would be generated
#
# The key insight is that we can model the xorshift algorithm symbolically
# and add constraints matching observed outputs to solve for the initial state.
import z3
import struct


# OBSERVED: 10 consecutive values generated by calling Math.random().
# Note: The V8 Math.random() implementation uses a cache that outputs values in
# reverse order (wrt xorshift outputs). The solve() function should handle this reversal internally.
OBSERVED = [0.4124579732430318, 0.6273067453454833, 0.2529277763090517, 0.6899475979298956, 0.10366597310560899, 0.15846902797021511, 0.43109057868542877, 0.872246337820732, 0.15570635111910935, 0.4614316386566165]

# EXPECTED: The 5 true next values that should be predicted.
# After reconstructing the internal state, our solver must predict exactly these values.
EXPECTED = [0.165998441995293, 0.5385817501266726, 0.9645538892138035, 0.6916489359038089, 0.0400179995419504]

EXPECTED_COUNT = 5

# TASK 1: Implement xorshift128+ algorithm using Z3 symbolic operations.
# 
# This function builds Z3 symbolic expressions that encode the xorshift128+
# state transformation. It takes symbolic bit vectors as input and returns
# symbolic expressions representing the next state and output.
#
# The implementation mirrors the C code from V8:
#   s1 = state0; s0 = state1;
#   s1 ^= s1 << 23;
#   s1 ^= s1 >> 17;
#   s1 ^= s0;
#   s1 ^= s0 >> 26;
#   return s0, s1, s0 + s1;
# 
# Hint: Use z3.LShR for logical right shift (zero-filled).
def XorShift128(state0: z3.AstRef, state1: z3.AstRef) -> tuple[z3.AstRef, z3.AstRef, z3.AstRef]:
    s1 = state0
    s0 = state1
    s1 = s1 ^ (s1 << 23)
    s1 = s1 ^ z3.LShR(s1, 17)
    s1 = s1 ^ s0
    s1 = s1 ^ z3.LShR(s0, 26)
    return s0, s1, s0 + s1



# TASK 2: Implement ToDouble conversion.
# 
# This function builds a Z3 symbolic expression that encodes the conversion
# from a 64-bit xorshift output to a double in [0,1). It takes a symbolic
# bit vector as input and returns a symbolic floating-point expression.
#
# The implementation mirrors the V8 ToDouble function:
#   1. Right shift by 11 to drop bits, keeping [0, 2^53)
#   2. Divide by 2^53 to get value in [0, 1)
#
# Hint: 
# - Use z3.LShR(out, 11) for logical right shift
# - Use z3.fpToFPUnsigned to convert bit vector to floating point
# - Create the denominator as z3.FPVal(str(1 << 53), z3.Float64())
# - Use z3.fpDiv to perform the division
def ToDouble(out: z3.AstRef) -> z3.AstRef:
    shifted = z3.LShR(out, 11)
    numerator = z3.fpToFPUnsigned(z3.RNE(), shifted, z3.Float64())
    denominator = z3.FPVal(str(1 << 53), z3.Float64())
    return z3.fpDiv(z3.RNE(), numerator, denominator)

# TASK 3: Complete the solve function to reconstruct the internal state.
# 
# This function builds a Z3 constraint model to reconstruct the PRNG state:
# - Creates symbolic variables for the internal state at each step
# - Uses XorShift128 and ToDouble to build symbolic expressions for transitions
# - Adds constraints matching observed outputs
# - Solves and extracts predicted values
#
# Important note: The cache outputs numbers in reverse order. This function should
# account for this by handling the reversal internally.
#
# Hint:
# 1. Create symbolic variables for the internal state (state0, state1) spanning
#    the number of steps needed to cover both the observed outputs plus additional
#    steps for predicting future values
# 2. Add constraints encoding the xorshift state transition between consecutive steps (with the XorShift128 function)
# 3. Add constraints matching the observed floating-point outputs to the solver's outputs (with the ToDouble function).
#    Use z3.fpToIEEEBV to compare floating-point values at the bit level for exact matching.
# 4. Solve the constraints to find a satisfiable model
# 5. Return the predicted outputs for the future values (in the correct order)
def solve(observed: list[z3.AstRef]) -> list[float] | None:
    solver = z3.Solver()

    num_steps = len(observed) + EXPECTED_COUNT
    states = [(z3.BitVec(f'state0_{i}', 64), z3.BitVec(f'state1_{i}', 64)) for i in range(num_steps)]

    # Transition constraints
    for i in range(num_steps - 1):
        s0, s1, out = XorShift128(states[i][0], states[i][1])
        solver.add(states[i + 1][0] == s0)
        solver.add(states[i + 1][1] == s1)

    # Observed output constraints
    for i in range(len(observed)):
        rev_index = num_steps - 1 - i
        _, _, out = XorShift128(states[rev_index][0], states[rev_index][1])
        predicted_fp = ToDouble(out)
        solver.add(z3.fpToIEEEBV(predicted_fp) == z3.fpToIEEEBV(observed[i]))

    if solver.check() == z3.sat:
        model = solver.model()
        predicted_values = []
        for i in range(EXPECTED_COUNT):
            _, _, out = XorShift128(states[i][0], states[i][1])
            predicted_fp = ToDouble(out)

            # Convert predicted_fp to python float
            bv = model.eval(z3.fpToIEEEBV(predicted_fp))
            bits = bv.as_long()
            # Pack as unsigned long long and unpack as double
            python_float = struct.unpack('d', struct.pack('Q', bits))[0]

            predicted_values.insert(0, python_float)
        return predicted_values
    else:
        return None

def main() -> None:
    # Convert observed floats to Z3 floating point values.
    observed_fp = [z3.FPVal(value, z3.Float64()) for value in OBSERVED]
    predicted = solve(observed_fp)
    assert predicted

    # Verify predictions match the actual next values in the sequence.
    for idx, (pred, exp) in enumerate(zip(predicted, EXPECTED)):
        if pred != exp:
            raise RuntimeError(
                f"Predicted value {idx} does not match observed next value."
            )
    print(predicted)


if __name__ == "__main__":
    main()
